FROM apache/spark:3.5.1

USER root
RUN pip install --no-cache-dir delta-spark==3.2.1

RUN mkdir -p /opt/app
WORKDIR /opt/app

COPY etl/ /opt/app/etl/
COPY data/ /opt/app/data/
RUN mkdir -p /opt/app/outputs

# MUST be after COPY (otherwise COPY reintroduces root-owned files)
RUN chown -R spark:spark /opt/app \
 && chmod -R u+rwX /opt/app

RUN mkdir -p /home/spark/.ivy2 \
 && chown -R spark:spark /home/spark/.ivy2

USER spark
