# Spark CLI image (gives you spark-submit)
FROM apache/spark:3.5.1

USER root

# Install kubectl inside this container
RUN apt-get update && apt-get install -y curl ca-certificates && \
    curl -LO "https://dl.k8s.io/release/$(curl -Ls https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl && \
    rm kubectl && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

ENV PATH="/opt/spark/bin:${PATH}"

# allow Spark/Ivy to download --packages jars
RUN mkdir -p /home/spark/.ivy2/cache /home/spark/.ivy2/jars && \
    chown -R spark:spark /home/spark/.ivy2

USER spark
WORKDIR /workspace